
const AUTHOR_ID = 'author_id',
FULL_STORY = 'full_story',
CREATED_AT = 'created_at',
ID='id',
TITLE= 'title',
THUMBNAIL='thumbnail',
SUMMARY='summary',
TAGS='tags',
LOCATION='location',
TYPE='type',
FULL_STORY_ID='full_story_id',
POST_ID='post_id',
PUBLISH_STATUS='publish_status',
MEDIA_URL = 'media_url',
FIRST_NAME ="first_name",
LAST_NAME = "last_name",
MIDDLE_NAME = "middle_name",
UUID = "uuid",
UNDEF = undefined,
STRATEGY_ID = 'strategy_id',
// USER_INFO_URL = 'https://www.googleapis.com/oauth2/v3/userinfo',
// REFRESH_TOKEN_URL = 'https://oauth2.googleapis.com/token',
STRATEGY_TYPE = 'strategy_type',
PROFILE_PIC_URL = 'profile_pic_url', 
EMAIL = 'email', 
LAST_LOGGED_AT = 'last_logged_at',
JOINED_AT = "created_at",
USER_UUID = 'user_uuid',
BOOKMARK_POST_ID='bookmark_post_id',
LIKES = 'likes',
VIEWS = 'views',
FOLLOWER_ID = 'follower_uuid',
FOLLOWEE_ID = 'following_uuid' 
;
export {
    UUID,
    ID,
    TITLE,
    TAGS,
    LOCATION,
    FIRST_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    PROFILE_PIC_URL,
    FULL_STORY,
    AUTHOR_ID,
    SUMMARY,
    FULL_STORY_ID,
    THUMBNAIL,
    TYPE,
    PUBLISH_STATUS,
    POST_ID,
    MEDIA_URL,
    CREATED_AT,
    UNDEF,
    STRATEGY_ID,
    STRATEGY_TYPE,
    EMAIL,
    LAST_LOGGED_AT,
    JOINED_AT,
    USER_UUID,
    BOOKMARK_POST_ID,
    LIKES,
    VIEWS,
    FOLLOWER_ID,
    FOLLOWEE_ID
}